name: yaaseen
description: Yasin sura.

version: 2.2.4+17

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  audio_service: ^0.18.7
  audioplayers: ^4.0.1
  badges: ^3.1.1
  connectivity_plus: ^3.0.2

  cupertino_icons: ^1.0.2
  firebase_analytics: ^10.0.4
  firebase_core: ^2.1.1
  firebase_messaging: ^14.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_local_notifications: ^13.0.0
  # flutter_screenutil: ^5.5.3+2
  flutter_svg: ^2.0.5
  freezed_annotation: ^2.2.0
  hive_flutter: ^1.1.0
  http: ^0.13.5
  in_app_review: ^2.0.4
  json_annotation: ^4.8.0
  just_audio: ^0.9.29
  on_click: ^1.1.3
  package_info_plus: ^3.0.1
  path_provider: ^2.0.11
  share_plus: ^6.2.0
  url_launcher: ^6.1.5
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.2.0

  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  hive_generator: ^2.0.0

  integration_test:
    sdk: flutter
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/icons/

  fonts:
    - family: Me-Quran
      fonts:
        - asset: assets/fonts/arabic/Me-Quran-Regular.ttf

    - family: Al-Qalam
      fonts:
        - asset: assets/fonts/arabic/al-qalam-kitab.ttf

    - family: Amiri
      fonts:
        - asset: assets/fonts/arabic/Amiri-Bold.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
